criaCartao(
    'Química',
    'O que são os hidrocarbonetos?',
    'Hidrocarbonetos são compostos formados apenas por carbono e hidrogênio.'
)

criaCartao(
    'Química',
    'Quais são os 4 tipos de hidrocarbonetos?',
    'São eles: Alcano, alceno, alcino e alcadieno.'
)

criaCartao(
    'Química',
    'Qual é o prefixo de um hidrocarboneto com 3 carbonos?',
    'Seu prefixo é prop.'
)

criaCartao(
    'Química',
    'Qual é o prefixo de um hidrocarboneto com 5 carbonos?',
    'Seu prefixo é pent.'
)

criaCartao(
    'Química',
    'Qual é o prefixo de um hidrocarboneto com 6 carbonos?',
    'Seu prefixo é Hex.'
)

criaCartao(
    'Química',
    'O que significa o infixo "an"?',
    'Significa que o hidrocarboneto possui ligações simples entre carbonos.'
)

criaCartao(
    'Química',
    'O que siginifica o infixo "en"',
    'Significa que o hidrocarboneto possui uma ligação dupla entre carbonos.'
)

criaCartao(
    'Química',
    'O que siginifica o infixo "in"',
    'Significa que o hidrocarboneto possui uma ligação tripla entre carbonos.'
)

criaCartao(
    'Química',
    'O que é um hidrocarboneto ramificado?',
    'É um hidrocarboneto cuja cadeia possui mais de duas extremidades'
)
