criaCartao(
    'Filosofia',
    'O que é a vida?',
    ' a vida é uma propriedade da matéria; é eterna e surge quando as condições se mostram propícias.'
)

criaCartao(
    'Filosofia',
    'quem foi o primeiro filosofo?',
    'Tales de Mileto.'
)

criaCartao(
    'Filosofia',
    'O qual era o maior problema para os pré-socráticos?',
    'Descobrir a arché.'
)

criaCartao(
    'Filosofia',
    'O que são pré-socráticos?',
    'são quaisquer filosofos  que surgirão antes de Socrates.'
)

criaCartao(
    'Filosofia',
    'O que é arché?',
    'se traduzindo do Grego, significada natureza de algo, e esse algo seria a natureza do próprio universo, sendo oque o deu origem.'
)

criaCartao(
    'Filosofia',
    'O que é um sofista?',
    'eram intelectuais como os filosofos, porem recebiam dinheiro por seus ensinamentos.'
)

criaCartao(
    'Filosofia',
    'O que siginifica filosofia?.'
    'Significa amor a sabedoria.'
)

criaCartao(
    'Filosofia',
    'o que é justiça',
    'E um conceito abstrato, onde seu significado muda de acordo com a pessoa, sendo normalmente é a particularidade do que é justo e correto, como o respeito à igualdade de todos os cidadãos.'
)

criaCartao(
    'Filosofia',
    'O que é um filosofo?',
    'qualquer pessoa que se questiona ou crítica uma verdade e busca compreendela ou apenas um amante do saber'
)
